<?xml version='1.1' encoding='UTF-8'?>
<!-- document type declaration (DTD) for the SEP Luna Rover mapping -->
<!-- Sem2, ->
!- Revision History
 
 Version 1.1
 Replaced mispelled vehicle and sequential
 
 Version 1.0
 Initial Release
 
 -->

<!DOCTYPE lunarrovermap [
  <!-- A Luna Rover map contianing one boundary, vehicle status, apollo landing site, rover landing site and track to color mapping, with any number of obstacles, zones, tracks and additional attributes. The Luna Rover map uses a global unit of mesurement for all measurmenets -->
  <!ELEMENT lunarovermap (attribute*, boundary, vehicle-status, apollo-landing-site, rover-landing-site, track-to-color, obstacle*, zone*, track*)>
  <!ATTLIST lunarovermap units (metres|km|cm|mm) "metres">

  <!-- The site boundray described as a rectangular area -->
  <!ELEMENT boundary (area)>

  <!-- The status of the vehicle with its location and heading -->
  <!ELEMENT vehicle-status (point, heading, attribute*)>

  <!-- An obstacle identified as the Apollo landing site -->
  <!ELEMENT apollo-landing-site (obstacle, attribute*)>

  <!-- A location identified as the luna rover landing site -->
  <!ELEMENT rover-landing-site (point, attribute*)>

  <!-- A mapping of track id to color codes - prototype mapping only -->
  <!ELEMENT track-to-color (attribute*)>

  <!-- An obstacle described as a set of contact points or an area surounding by the obstacle -->
  <!ELEMENT obstacle ((point+)|area)>

  <!-- A zone with a circle or shape descriping the enclosed region of the zone and its state -->
  <!ELEMENT zone (attribute*, (circle|area) )>
  <!ATTLIST zone 
  	state (nogo|unexplored|explored|radiation|crater) #REQUIRED>

  <!-- A series or points describing the shape and length of a track with sequential point elements -->
  <!ELEMENT track ((point+|area), attribute*)>
  <!ATTLIST track 
  	type (landing|vehicle|footprint) #REQUIRED>

  <!-- An area with one or more points describing its shape -->
  <!ELEMENT area (point+)>

  <!-- A circle contians a point of origin with a radius attribute -->
  <!ELEMENT circle (point)>
  <!ATTLIST circle
    radius CDATA #REQUIRED>

  <!-- A point is specified on a 2D cartisean plane. X progresses horizontally to the right, y progresses vertially and upwards. -->
  <!ELEMENT point EMPTY>
  <!ATTLIST point 
      x CDATA #REQUIRED
      y CDATA #REQUIRED>
  
  <!-- General Attributes definition -->
  <!ELEMENT attribute (key,value)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<!-- Sample luna rover map -->
<lunarovermap units="metres">
  <attribute>
    <key>Survey Date</key>
    <value>01/01/2017</value>
  </attribute>

  <attribute>
    <key>Robot Model</key>
    <value>Lego Mindstorm EV3</value>
  </attribute>

  <boundary>
    <area>
      <point x="30" y="50"/>
      <point x="810" y="50"/>
      <point x="810" y="490"/>
      <point x="30" y="490"/>
    </area>
  </boundary>
  
  <vehicle-status>
    <point x="700" y="100"/>

    <attribute>
      <key>heading</key> <!-- in degress -->
      <value>180</value> <!-- 0 is north, increasing CW -->
    </attribute>
  </vehicle-status>

  <apollo-landing-site>
  	<point x="632" y="197"/>
  </apollo-landing-site>

  <rover-landing-site>
  	<point x="810" y="510"/>
  </rover-landing-site>

  <obstacle>
    <point x="351" y="100"/>
    <point x="355" y="108"/>
    <point x="360" y="117"/>
    <point x="360" y="125"/>
  </obstacle>

  <track-to-color>
    <attribute>    
 	  <key>vechile</key> <!-- type of the track -->
      <value>0000FF</value> <!-- blue -->
    </attribute>
    <attribute>
      <key>footprint</key>
      <value>FF0000</value> <!-- red -->
    </attribute>
    <attribute>
      <key>landing</key>
      <value>00FF00</value> <!-- green -->
    </attribute>
  </track-to-color>

  <zone state="explored">
    <area>                                            
      <point x="20" y="35"/>
      <point x="0" y="35"/>
      <point x="0" y="18"/>
      <point x="16" y="18"/>
      <point x="16" y="20"/>
      <point x="20" y="20"/>
    </area>
  </zone>
  
  <zone state="nogo">
    <circle radius="52">
      <point x="355" y="270"/>
    </circle>
  </zone>

  <zone state="nogo">
    <area>
      <point x="307" y="449"/>
      <point x="307" y="384"/>
      <point x="367" y="324"/>
      <point x="367" y="449"/>
    </area>
  </zone>

  <zone state="crater">
    <area>
      <point x="251" y="110"/>
      <point x="290" y="133"/>
      <point x="307" y="180"/>
      <point x="298" y="235"/>
      <point x="227" y="304"/>
      <point x="150" y="311"/>
      <point x="115" y="283"/>
      <point x="100" y="174"/>
      <point x="110" y="138"/>
      <point x="113" y="106"/>
      <point x="174" y="100"/>
    </area>
  </zone>

  <zone state="radiation">
    <area>
      <point x="570" y="179"/>
      <point x="607" y="151"/>
      <point x="654" y="151"/>
      <point x="675" y="170"/>
      <point x="684" y="214"/>
      <point x="667" y="262"/>
      <point x="624" y="287"/>
      <point x="578" y="276"/>
      <point x="557" y="242"/>
    </area>
  </zone>

  <zone state="unexplored">
    <area>
      <point x="30" y="50"/>
      <point x="100" y="50"/>
      <point x="100" y="490"/>
      <point x="30" y="490"/>
    </area>
  </zone>

  <track type="vehicle">
    <point x="600" y="195"/>
    <point x="490" y="165"/>
    <point x="375" y="165"/>
  </track>

  <track type="footprint">
    <point x="630" y="228"/>
    <point x="610" y="269"/>
    <point x="600" y="324"/>
    <point x="608" y="376"/>
    <point x="632" y="418"/>
  </track>

  <track type="landing">
    <point x="704" y="77"/>
    <point x="737" y="100"/>
    <point x="682" y="215"/>
    <point x="675" y="170"/>
    <point x="654" y="151"/>
    <point x="605" y="151"/>
  </track>

</lunarovermap>

